outline_template_v0010 = [
    "Below is a segment from the outline of my story titled '{title}'. Based on this segment: {prompt}. Could you expand upon this by creating a numbered list (1-10) that outlines a series of events for this part of the story? Please ensure each event is detailed and contributes to the development of the plot or characters. Also, consider the logical progression of events and how they connect to the overall narrative. This list should help in further fleshing out the story's structure and guide the subsequent drafting process.",
    "Here is a section from the outline of my story titled {title}. Based on this outline: {prompt}. Please write this part of the story in a detailed narrative prose format, focusing on descriptive storytelling. Include descriptions of settings, characters' thoughts and dialogue, and actions, and ensure the story flows smoothly from one scene to the next. Avoid presenting the story as a script or an outline. Fill in the gaps as necessary to create a cohesive and engaging narrative.",
    "Below is a segment from the rough draft of my story titled '{title}'. {prompt}. Could you revise this to make the narrative more cohesive? Focus on improving the flow of events, enhancing character development, and ensuring that the transitions between scenes are smooth. Additionally, please look for any inconsistencies in the plot or character actions and address them. My goal is to have a seamless narrative that clearly conveys the story's progression and deepens the reader's engagement with the characters and their journey."
]

summary_template_v0001 = [
    "Here is a summary of the story '{title}':\n{summary}\nCan you flesh out this summary, filling in the gaps where necessary but staying true to every aspect of the original summary?",
    "Here is a summary of the story '{title}':\n{summary}\nCan you split this summary into 24 parts that logically flow together, filling in the gaps where necessary but staying true to every aspect of the original summary?",
    "Here is a summary of the story '{title}': \n{summary}\nHere are the 24 parts of the story: {parts}\nCan you write this specific part of the story in a detailed narrative prose format, focusing on 3rd person descriptive storytelling, also filling in the gaps where necessary but staying true to every aspect of the original summary?: {part}",
    "Can you make these two sections more cohesize?: \n{section1}\n{section2}"
]

summary_template_v0002 = [
    "Here is a summary of the story '{title}':\n{summary}\n I need you to expand it into a more detailed narrative. Please incorporate vivid descriptions of characters, settings, and key events. Introduce dialogue where appropriate to bring characters to life, and develop subplots that enrich the main storyline. Ensure each aspect of the summary is explored with depth, creating immersive scenes that engage the reader fully.",
    "Here is a summary of the story '{title}':\n{summary}\nDivide the story into 24 cohesive chapters, based on the summary provided. For each chapter, outline the primary focus, key events, character developments, and how it contributes to the overall arc of the story. Ensure each chapter opens and concludes in a manner that propels the story forward, maintaining narrative tension and thematic coherence throughout.",
    "Here is a summary of the story '{title}': \n{summary}\nHere are the 24 parts of the story: {parts}\nDevelop a detailed chapter based on the chapter summary below using third-person narrative. Incorporate sensory descriptions to paint vivid scenes, deepen character insights with internal monologues, and craft meaningful dialogue that reveals character dynamics and advances the plot. Ensure the chapter's events are seamlessly integrated with the story's overall themes and contribute significantly to character development and plot progression: {part}",
    "Enhance the cohesion between the following two sections: \n{section1}\n{section2}\nPlease intertwine these sections by adding transitional phrases, ensuring character motivations and story developments are consistent across both. Introduce reflections or events that logically connect the sections, smoothing any abrupt narrative jumps and aligning the tone and pacing."
]